<?xml version="1.0" ?>
<!-- 
	The dictionary key is used in the system to get a handle to the type 
	of dictionary (see DictionaryManager for more information).
	The version node key is used in the caching and per-project settings.
	
	When CFE starts it will load up the first version in each dictionary.
	If another project is then created (or switched to) then any other
	needed dictionaries will be loaded and cached. So, if you put the one 
	you use	most at the top you'll gain a touch of speed.
	
	Also note at present you will only get one SQL file grammer / version
	no matter how many CF version you are using. Meaning it is not 
	possible to configure cfmx701 with SQL Server *and* bd61 with MYSQL 
	server grammer at the same time.
-->
<!DOCTYPE dictionary_config [
	<!ELEMENT dictionary_config (dictionary+)>
	<!ELEMENT dictionary (version+)>
	<!ATTLIST dictionary
		id ID #REQUIRED
	>
	<!ELEMENT version (grammer+)>
	<!ATTLIST version
		key ID #REQUIRED
		label CDATA #REQUIRED
	>
	<!ELEMENT grammer EMPTY>
	<!ATTLIST grammer
		location CDATA #REQUIRED
	>
]>
<dictionary_config>
	<dictionary id="CF_DICTIONARY">
		<version key="cfmx701" label="Coldfusion 7.0">
			<grammer location="cfml.xml" />
			<grammer location="user.xml" />
		</version>
		<version key="bd61" label="BlueDragon 6.1">
			<grammer location="cfmlBD61.xml" />
			<grammer location="user.xml" />
		</version>
	</dictionary>

	<dictionary id="JS_DICTIONARY">
		<version key="ecma" label="ECMA Javascript">
			<grammer location="js.xml" />
		</version>
	</dictionary>

	<!-- note that this will get loaded into the CFML dictionary -->
	<dictionary id="SQL_DICTIONARY">
		<version key="mssql" label="Microsoft(R) SQL Server">
			<grammer location="sqlkeywords.txt" />
		</version>
	</dictionary>
	
	<dictionary id="HT_DICTIONARY">
		<version key="xhtml" label="XHTML">
			<grammer location="html.xml" />
		</version>
	</dictionary>
	
</dictionary_config>