=== JLLeitschuh/cfeclipse/cvs/trunk/src/version1/predictionary/dictionary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="dictionary">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="tags"/>
				<xs:element minOccurs="0" ref="functions"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="tags">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="tag"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="tag">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="help"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="parameter"/>
			</xs:sequence>
			<xs:attribute name="creator" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="single" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="xmlstyle" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="functions">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="function"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="function">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="help"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="parameter"/>
			</xs:sequence>
			<xs:attribute name="creator" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="returns" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="String"/>
						<xs:enumeration value="Numeric"/>
						<xs:enumeration value="Object"/>
						<xs:enumeration value="Query"/>
						<xs:enumeration value="Array"/>
						<xs:enumeration value="boolean"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="help"/>
				<xs:element minOccurs="0" ref="values"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="String"/>
						<xs:enumeration value="Numeric"/>
						<xs:enumeration value="Object"/>
						<xs:enumeration value="Query"/>
						<xs:enumeration value="Array"/>
						<xs:enumeration value="boolean"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="required" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="values">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="value">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="option" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="help" type="xs:string"/>
	
</xs:schema>

=== JLLeitschuh/cfeclipse/cvs/trunk/src/frameworks/fusebox4/dictionary/fusedoc.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Jason L. West (WezBiz Technologies) -->
<dictionary xmlns="http://www.cfeclipse.org/version1/dictionary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cfeclipse.org/version1/dictionary http://www.cfeclipse.org/version1/dictionary/dictionary.xsd">
	<tags>
		<tag name="fusedoc" creator="8" single="false" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
			<parameter name="fuse" type="String" required="true">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
			<parameter name="language" type="String" required="true">
				<help><![CDATA[Need to add help]]></help>
				<values>
					<value option="CFML"/>
					<value option="PHP 4"/>
					<value option="PHP 5"/>
					<value option="JSP"/>
					<value option="LASSO"/>
				</values>
			</parameter>
			<parameter name="version" type="String" required="true">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="2.0"/>
				</values>
			</parameter>
		</tag>
		<tag name="responsibilities" creator="8" single="false" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
		</tag>
		<tag name="properties" creator="8" single="false" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
		</tag>
		<tag name="history" creator="8" single="false" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
			<parameter name="author" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
			<parameter name="email" type="Any" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
			<parameter name="type" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="create"/>
					<value option="update"/>
				</values>
			</parameter>
			<parameter name="date" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
			<parameter name="role" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="Architect"/>
					<value option="FuseCoder"/>
					<value option="DBA"/>
					<value option="Graphics"/>
					<value option="Text Editor"/>
				</values>
			</parameter>
		</tag>
		<tag name="property" creator="8" single="true" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
			<parameter name="name" type="String" required="true">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
			<parameter name="value" type="String" required="true">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
		</tag>
		<tag name="note" creator="8" single="false" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
			<parameter name="author" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
			<parameter name="date" type="DateTime" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
		</tag>
		<tag name="io" creator="8" single="false" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
		</tag>
		<tag name="in" creator="8" single="false" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
		</tag>
		<tag name="out" creator="8" single="false" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
		</tag>
		<tag name="string" creator="8" single="true" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
			<parameter name="name" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
			<parameter name="scope" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="application"/>
					<value option="attributes"/>
					<value option="caller"/>
					<value option="cgi"/>
					<value option="client"/>
					<value option="form"/>
					<value option="formorurl"/>
					<value option="request"/>
					<value option="server"/>
					<value option="session"/>
					<value option="url"/>
					<value option="variables"/>
				</values>
			</parameter>
			<parameter name="comments" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="mask" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="onCondition" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="format" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="cfml"/>
					<value option="wddx"/>
					<value option="xml"/>
				</values>
			</parameter>
			<parameter name="optional" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="true"/>
					<value option="false"/>
				</values>
			</parameter>
			<parameter name="default" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="passthrough" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="editable" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="true"/>
					<value option="false"/>
				</values>
			</parameter>
		</tag>
		<tag name="number" creator="8" single="true" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
			<parameter name="name" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
			<parameter name="scope" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="application"/>
					<value option="attributes"/>
					<value option="caller"/>
					<value option="cgi"/>
					<value option="client"/>
					<value option="form"/>
					<value option="formorurl"/>
					<value option="request"/>
					<value option="server"/>
					<value option="session"/>
					<value option="url"/>
					<value option="variables"/>
				</values>
			</parameter>
			<parameter name="comments" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="precision" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="decimal"/>
					<value option="integer"/>
				</values>
			</parameter>
			<parameter name="onCondition" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="optional" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="true"/>
					<value option="false"/>
				</values>
			</parameter>
			<parameter name="default" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="passthrough" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="editable" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="true"/>
					<value option="false"/>
				</values>
			</parameter>
		</tag>
		<tag name="boolean" creator="8" single="true" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
			<parameter name="name" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
			<parameter name="scope" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="application"/>
					<value option="attributes"/>
					<value option="caller"/>
					<value option="cgi"/>
					<value option="client"/>
					<value option="form"/>
					<value option="formorurl"/>
					<value option="request"/>
					<value option="server"/>
					<value option="session"/>
					<value option="url"/>
					<value option="variables"/>
				</values>
			</parameter>
			<parameter name="comments" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="onCondition" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="optional" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="true"/>
					<value option="false"/>
				</values>
			</parameter>
			<parameter name="default" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="true"/>
					<value option="false"/>
				</values>
			</parameter>
			<parameter name="passthrough" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
			</parameter>
			<parameter name="editable" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="true"/>
					<value option="false"/>
				</values>
			</parameter>
		</tag>
		<tag name="datetime" creator="8" single="true" xmlstyle="true">
			<help><![CDATA[Need to add help here]]></help>
			<parameter name="name" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values/>
			</parameter>
			<parameter name="scope" type="String" required="false">
				<help><![CDATA[Need to add help here]]></help>
				<values>
					<value option="application"/>
					<value option="attributes"/>
					<value option="caller"/>
					<value option="cgi"/>
					<value option="client"/>
